In [1]:
print("Hello, Chris and Daliah!")

Hello, Chris and Daliah!


In [2]:
print("Hello, Chris and Daliah!, testing functional branch") #comment test

Hello, Chris and Daliah!, testing functional branch


# Task 1: Project Phase I Summary

1.1 - Restate the selected problem, dataset, target variable, and prediction objective. 

The selected problem for this project is to determine the critically ill patients' state after 2 months of entering the study. This project is built around the dataset to cater to this specific group of individuals from 1989 to 1991. However, it is envisioned that this data set may be used for machine learning to determine a patient's state in the current world with the aim of providing better health care and medical choices. The data set discussed is called the SUPPORT2 dataset, published on the UCI Machine Learning Repository. The target variable for this project is sfdm2, which comprises the following subcategories:

(Note: the subcategories are ordered in severity, with 1 being the lowest and 5 being the highest.)

- Level 1: no(Month 2 and SIP pres) - patients show no moderate or severe functional disability.

- Level 2: (adl >= 4) - patients struggling with completing 4 or more daily activities.

- Level 3: (SIP >=) - patients with a sickness profile of equal to or greater than 30.

- Level 4 (Coma or Intub) - patients in coma or intubated.

- Level 5: ( < 2 mo.follow-up) - patients have passed before the check-up.

The objective of this prediction, as stated above, is to predict a patient's state after 2 months to cater to health-care and medical decisions to better end-of-life support and care.


1.2 - Summarise the dataset source, number of records, number of features, and main data characteristics. 

The SUPPORT2 dataset was acquired from the UCI Machine Learning Repository. Below is a table created to summarize the data.

| Title | Description |
|---|---|
| Dataset | SUPPORT2 |
| Source | UCI Machine Learning Repository |
| License | Creative Commons Attribution 4.0 International (CC BY 4.0) |
| Collection | Patient interviews and clinical information |
| Dataset characteristics | Tabular and multivariate |
| Feature types | Integer, categorical, and real |
| Instances | 9,105 |
| Features | 42 |

After cleaning the data set, the remaining instances and features are:

Instances: 23
Features: 7181

A summarized table has been made upon writing the Phase 1 progress report to describe the most relevant features. Columns left blank are self-explanatory by name.

| Name | Type | Description | Additional Information |
|---|---|---|---|
| sex | Categorical | Patient's sex | Male, female |
| dzgroup | Categorical | Disease or illness subcategory | ARF/MOSF with sepsis, CHF, COPD, lung cancer, MOSF with malignancy, coma, colon cancer, and cirrhosis |
| dzclass | Categorical | Disease classification | ARF/MOSF, COPD/CHF/cirrhosis, cancer, and coma |
| ca | Categorical | Cancer status | Metastatic cancer, cancer, or no cancer |
| dnr | Categorical | Whether the patient has a “Do Not Resuscitate” order | — |
| sfdm2 | Categorical | Patient's functional disability at the two-month follow-up | `<2 mo. follow-up`, `no (M2 and SIP pres)`, `ADL >= 4 (>= 5 if sur)`, `SIP >= 30`, or `coma or intubation` |
| hospdead | Numerical | Whether the patient died in hospital | — |
| slos | Numerical | Number of days from study entry to discharge | The start date is when the patient entered the study |
| scoma | Numerical | SUPPORT model coma score | Based on the Glasgow Coma Scale |
| charges | Numerical | Hospital charges assigned to the patient | — |
| avtisst | Numerical | Average TISS score | The Therapeutic Intervention Scoring System is used to estimate costs for severely ill patients in the ICU or IMCU |
| sps | Numerical | SUPPORT physiology score measured on day three | The score is predicted using a model |
| meanbp | Numerical | Mean blood pressure | — |
| wblc | Numerical | White blood cell count | — |
| hrt | Numerical | Heart rate measured on day three | — |
| resp | Numerical | Respiratory rate measured on day three | — |
| adlp | Numerical | Activities of Daily Living (ADL) index completed by the patient | Measured on day three and reflects the difficulty the patient experiences with everyday activities |

1.3 - Briefly describe the main data-quality issues identified in Phase I. 

The main data-quality issue found in Phase I consists of missing values. For sfdm2, a total of 1400 missing records were discovered, which results in a loss of valuable information. As sfdm2 is the target variable, these missing instances had to be removed. Lots of missing values were seen in certain features such as urine, adlp, and glucose, which can also affect the integrity of this project as more reliance will need to go to other features.

Some data had peculiar ranges; not all of these were discounted, as outliers are expected due to the patients being critically ill. E.g, the heart rate range was 0-300 bpm, which is impossible for the scenario that these patients were interviewed outside of an ongoing medical emergency. In this case, some outliers were removed if appropriate; certain features were removed as there were too many missing values; or independent variables were removed to determine patient state; an example is the prg2m/prg6m variables, which were a physician's survival predictions for the patient (do not directly relate to patient health).

1.4 - Explain why the problem is suitable for an LCS-based solution. 

This problem is suitable for an LCS-based solution because it can handle multi-class problems, including this one, which contains both categorical and numerical features. In the first phase, heatmaps revealed weak linear correlations between the features themselves and the target variable (sfdm2). The learning classifier system will be useful for this problem, as it is adept at handling and identifying complex relationships where linear relationships may fail. Another highlight of using the LCS-based solution for this problem is its transparency in comparison to a black box, as the features and variables related to the sfdm2 variable are important for health-care and medical teams since they provide elaboration on the predicted outcome, which allows teams to make better medical decisions for the patient.



# Task 2: Running an Original eLCS on the Raw SUPPORT2 dataset.
* Select an appropriate LCS variant, preferably eLCS.
* Use the original LCS code without algorithmic modification.
* Run the original LCS system on the raw or minimally processed dataset.
* Report the selected LCS parameters.
* Record the baseline performance results.
* Explain any minimal processing required to make the dataset compatible with the LCS code.

For Jono and Daaliah: pip install scikit-elcs run this in your terminal to get the eLCS, same one from LCS labs. 

In [3]:
import numpy as np
import pandas as pd

from skeLCS import eLCS

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import inspect

print("eLCS loaded from:")
print(inspect.getfile(eLCS))

eLCS loaded from:
c:\Users\itsjo\AppData\Local\Programs\Python\Python314\Lib\site-packages\skeLCS\eLCS.py


In [4]:
df_raw = pd.read_csv("support2.csv")

print(df_raw.shape)
display(df_raw.head())
print(df_raw.dtypes.value_counts()) 
# loading the dataset and displaying its shape, first few rows, and data types of each column.
# this is teh raw dataset df_raw

df_baseline = df_raw.copy(deep=True) 
# preservation of the original dataset for baseline comparison. 
# task 2 is the baseline which will be used to compare the performance of the eLCS model later on. 

(9105, 47)


,age,death,sex,hospdead,slos,d.time,dzgroup,dzclass,num.co,edu,...,crea,sod,ph,glucose,bun,urine,adlp,adls,sfdm2,adlsc
1,62.84998,0,male,0,5,2029,Lung Cancer,Cancer,0,11.0,...,1.199951,141.0,7.459961,NaN,NaN,NaN,7.0,7.0,NaN,7.0
2,60.33899,1,female,1,4,4,Cirrhosis,COPD/CHF/Cirrhosis,2,12.0,...,5.500000,132.0,7.250000,NaN,NaN,NaN,NaN,1.0,<2 mo. follow-up,1.0
3,52.74698,1,female,0,17,47,Cirrhosis,COPD/CHF/Cirrhosis,2,12.0,...,2.000000,134.0,7.459961,NaN,NaN,NaN,1.0,0.0,<2 mo. follow-up,0.0
4,42.38498,1,female,0,3,133,Lung Cancer,Cancer,2,11.0,...,0.799927,139.0,NaN,NaN,NaN,NaN,0.0,0.0,no(M2 and SIP pres),0.0
5,79.88495,0,female,0,16,2029,ARF/MOSF w/Sepsis,ARF/MOSF,1,NaN,...,0.799927,143.0,7.509766,NaN,NaN,NaN,NaN,2.0,no(M2 and SIP pres),2.0


float64    31
int64       8
str         8
Name: count, dtype: int64


In [5]:
target = "sfdm2" # target variable for the classification task, which is the column 'sfdm2' in the dataset.

print(df_baseline[target].value_counts(dropna=False)) # inspection of the target variable. 

# incomplete values are expected in df_raw. 

df_baseline = df_baseline.dropna(subset=[target]).copy()
print("Rows after removing missing target:", len(df_baseline))
# because of the way eLCS works, the taget variables must not contain "NaN", only numerical values so this will 
# be an example of minimal preprocessing. 
# a supervised learning algorithm like eLCS requires a complete target
#  variable to learn from the data, which is why we have dropped na. 

sfdm2
<2 mo. follow-up       3123
no(M2 and SIP pres)    3061
NaN                    1400
adl>=4 (>=5 if sur)     916
SIP>=30                 564
Coma or Intub            41
Name: count, dtype: int64
Rows after removing missing target: 7705


In [6]:
# another thing is that scikit-eLCS supports continuous and discrete attributes, mixed feature types and 
# missing predictor values, but its core estimator expects the data passed into fit() to be numeric. 

# so strings will have to be encoded into numbers. sorry jono ily <3
X_df = df_baseline.drop(columns=[target]).copy()
y_raw = df_baseline[target].copy()

categorical_cols = X_df.select_dtypes(
    include=["object", "string", "category"]
).columns

print("Categorical predictors:")
print(categorical_cols.tolist()) # identify categorical columns in the dataset.

category_mappings = {}

for col in categorical_cols:
    codes, labels = pd.factorize(X_df[col], sort=True)

    X_df[col] = codes.astype(float)

    # factorize represents missing values as -1.
    # Put these back to NaN because eLCS supports missing predictor values.
    X_df.loc[X_df[col] == -1, col] = np.nan

    category_mappings[col] = labels.tolist()

    # numbers do not have hierarchy, 3 > 2 is not true. 

Categorical predictors:
['sex', 'dzgroup', 'dzclass', 'income', 'race', 'ca', 'dnr']


In [7]:
# the target variable is also categorical, so it will be encoded as well.
# but separately. 

target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y_raw)

X = X_df.to_numpy(dtype=float)

print("Target mapping:") # so we know what the encoded values mean.

for i, class_name in enumerate(target_encoder.classes_):
    print(i, "=", class_name)

#data check. 
print("X shape:", X.shape)
print("y shape:", y.shape)

print("Missing predictor values:", np.isnan(X).sum())
print("Missing target values:", pd.isna(y).sum())
# Predictor missingness doesn't matter, eLCS can handle that naturally. 
# target missingness is 0, good. eLCS requires a complete target variable to learn from the data.

Target mapping:
0 = <2 mo. follow-up
1 = Coma or Intub
2 = SIP>=30
3 = adl>=4 (>=5 if sur)
4 = no(M2 and SIP pres)
X shape: (7705, 46)
y shape: (7705,)
Missing predictor values: 36948
Missing target values: 0


In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
) # test train split, 80% training, 20% testing, this matches the later split as well so might as well use the same split. 

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

# stratify=y? sfdm2 is imbalanced, so stratifying the split ensures that both the training and test sets have a similar 
# distribution of the target classes. This is important for model evaluation, as it helps to avoid bias in the performance 
# metrics due to class imbalance.

print("Training class distribution:")
print(pd.Series(y_train).value_counts(normalize=True).sort_index())

print("\nTesting class distribution:")
print(pd.Series(y_test).value_counts(normalize=True).sort_index())

Training set: (6164, 46)
Test set: (1541, 46)
Training class distribution:
0    0.405256
1    0.005354
2    0.073167
3    0.118916
4    0.397307
Name: proportion, dtype: float64

Testing class distribution:
0    0.405581
1    0.005191
2    0.073329
3    0.118754
4    0.397145
Name: proportion, dtype: float64


In [9]:
# implementation beginss. 
baseline_elcs = eLCS(
    random_state=42
)
# this is our baseline model, with default parameters everywhere, those parameters is what we will be tuning
# once we move further into the tasks. 
# below are the default values from scikit-eLCS. 
#learning_iterations = 10000
#N = 1000
#p_spec = 0.5
#nu = 5
#chi = 0.8
#mu = 0.04
#theta_GA = 25
#selection_method = tournament

params = baseline_elcs.get_params()

params_df = pd.DataFrame(
    params.items(),
    columns=["Parameter", "Value"]
)

display(params_df) # this function displays the parameters of the baseline eLCS model in a tabular format,
#making it easier to review and understand the configuration of the model before training.

# gonna save it to a csv for later reference.
# this also makes reporting easier. 
params_df.to_csv(
    "task2_original_elcs_parameters.csv",
    index=False
)

,Parameter,Value
0,N,1000
1,acc_sub,0.99
2,beta,0.2
3,chi,0.8
4,delta,0.1
5,discrete_attribute_limit,10
6,do_GA_subsumption,True
7,do_correct_set_subsumption,False
8,fitness_reduction,0.1
9,init_fit,0.01


In [10]:
baseline_elcs.fit(X_train, y_train); 
print("eLCS training complete.")

# do not remove the ; idky but the scikit-eLCS output is such that jupyter clashes with it,
# so it will train perfectly fine but just wont show you nicely. ; makes it so that the chunk runs but doesnt display. 
# we can view it later= 

# boom thats the whole thing. thats our model. 
# whats actually happening in here tho? its happening in order, 1 > 2 > 3

# 1. take current patient (instance) - dont lose track of the current patient,
# 2. construct match set [M], match set is the collection of classifiers that match the current instance based on their conditions. 
# 3. construct correct set [C], the subset of the match set that contains classifiers that correctly classify the current instance.
# 4. update rule parameters/fitness 

# 5. maybe performs subsumption, which is the process of replacing a more specific classifier with a more 
# general one if the general one has better performance.

# 6. maybe performs GA genetic algorithm, which is a search heuristic that mimics the process of natural selection to
# generate high-quality solutions for optimization and search problems.

# 7. crossover/mutation generate rules. 
# 8. delete rules if the population size exceeds the maximum allowed size.
# 9. next patient (instance), repeats. each. time. 

# important note: learning_interations = 10000, means 10,000 individual learning cycles. 

eLCS training complete.


In [11]:
print("Training completed:", baseline_elcs.hasTrained)
print("Iterations completed:", baseline_elcs.explorIter)
print("Number of rules:", len(baseline_elcs.population.popSet))

Training completed: True
Iterations completed: 10000
Number of rules: 948


In [12]:
y_pred = baseline_elcs.predict(X_test)
# what is this? this is the prediction step, 
# where the trained eLCS model is used to predict the 
# target variable for the test set instances.

# an important note for later:
# baseline_elcs.score(X_test, y_test)
# the eLCS model overrides this and returns balanced score, not ordinary accuracy. 

# whats the point?
# baseline_elcs.score(xxxxx) should not be labeled as accuracy, because it is not. it is balanced accuracy.

accuracy = accuracy_score(y_test, y_pred)

balanced_acc = balanced_accuracy_score(
    y_test,
    y_pred
)

precision_macro = precision_score(
    y_test,
    y_pred,
    average="macro",
    zero_division=0
)

recall_macro = recall_score(
    y_test,
    y_pred,
    average="macro",
    zero_division=0
)

f1_macro = f1_score(
    y_test,
    y_pred,
    average="macro",
    zero_division=0
)

# all of these are to be stored and saved. 
baseline_results = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Balanced Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1"
    ],
    "Value": [
        accuracy,
        balanced_acc,
        precision_macro,
        recall_macro,
        f1_macro
    ]
})

display(baseline_results)

baseline_results.to_csv(
    "task2_original_elcs_results.csv",
    index=False
) # this is saved to a CSV aswell since everything we do later will be compared to this, nice to have a seprate 
# file for it, ya feel?

print(
    classification_report(
        y_test,
        y_pred,
        target_names=target_encoder.classes_,
        zero_division=0
    )
)

cm = confusion_matrix(y_test, y_pred)

cm_df = pd.DataFrame(
    cm,
    index=target_encoder.classes_,
    columns=target_encoder.classes_
)

display(cm_df)

,Metric,Value
0,Accuracy,0.718365
1,Balanced Accuracy,0.358928
2,Macro Precision,0.343498
3,Macro Recall,0.358928
4,Macro F1,0.322452


                     precision    recall  f1-score   support

   <2 mo. follow-up       0.82      0.85      0.83       625
      Coma or Intub       0.00      0.00      0.00         8
            SIP>=30       0.00      0.00      0.00       113
adl>=4 (>=5 if sur)       0.25      0.01      0.01       183
no(M2 and SIP pres)       0.65      0.94      0.77       612

           accuracy                           0.72      1541
          macro avg       0.34      0.36      0.32      1541
       weighted avg       0.62      0.72      0.64      1541



,<2 mo. follow-up,Coma or Intub,SIP>=30,adl>=4 (>=5 if sur),no(M2 and SIP pres)
<2 mo. follow-up,530,0,0,1,94
Coma or Intub,3,0,0,0,5
SIP>=30,19,0,0,2,92
adl>=4 (>=5 if sur),62,2,0,1,118
no(M2 and SIP pres),35,0,1,0,576


In [13]:
# super handy, we can export the learned rules. Pretty sure this pops up later so I think saving the 
# initial rules could be useful.
baseline_elcs.export_final_rule_population(
    headerNames=np.array(X_df.columns),
    className="sfdm2",
    filename="task2_original_elcs_rules.csv"
)

# and 

baseline_elcs.export_iteration_tracking_data(
    "task2_original_elcs_tracking.csv"
)

# theres an issue I wanna raise tho, this minimally processed dataset which the model has been trained on access to 
# the future variables... do we want that? or should future variable cleansing count as minimal preprocessing? 
# see what yall think. 

# > [Jono]: I doubt we want one model to have access to both so we should train a sperate one in task 4 imo

# Task 3: Data Preprocessing and Feature Engineering
* Address missing values, duplicate records, invalid values, inconsistent categories, and incorrect data types. 
* Investigate and handle outliers where appropriate. 
* Encode categorical variables and scale, discretise, or transform numerical variables where required. 
* Address class imbalance where relevant. 
* Apply feature engineering, feature selection, or dimensionality reduction where justified. 
* Clearly explain how preprocessing is expected to improve LCS performance. 
* Ensure that preprocessing avoids data leakage. 

For Chris and Daliah: pip install imblearn

In [14]:
# Create a new dataframe for cleaning
df_clean = df_raw.copy(deep=True)

string_cols = df_clean.select_dtypes(include=['object']).columns

# Define explicit category orders for features where the ordering is meaningful
# (rather than arbitrary, as pd.factorize would assign by order of appearance)
category_orders = {
    'sfdm2': [
        'no(Month 2 and SIP pres)',   # 0: least severe
        'adl>=4 (>=5 if sur)',        # 1
        'SIP>=30',                    # 2
        'Coma or Intub',              # 3
        '<2 mo. follow-up'            # 4: most severe
    ]
}

# Create a new enum column for each feature of string data type, suffixed with '_enum'
for col in string_cols:
    if col in category_orders:
        cat = pd.Categorical(df_clean[col], categories=category_orders[col], ordered=True)
        df_clean[col + '_enum'] = cat.codes
    else:
        df_clean[col + '_enum'] = pd.factorize(df_clean[col])[0]

    mapping = df_clean[[col, col + '_enum']].drop_duplicates().sort_values(col + '_enum')
    print(f"\n{col} mapping:")
    print(mapping)

# Drop the original string columns, keeping their _enum replacements
df_clean = df_clean.drop(columns=string_cols)


sex mapping:
      sex  sex_enum
1    male         0
2  female         1

dzgroup mapping:
              dzgroup  dzgroup_enum
1         Lung Cancer             0
2           Cirrhosis             1
5   ARF/MOSF w/Sepsis             2
6                Coma             3
7                 CHF             4
10       Colon Cancer             5
26               COPD             6
28       MOSF w/Malig             7

dzclass mapping:
              dzclass  dzclass_enum
1              Cancer             0
2  COPD/CHF/Cirrhosis             1
5            ARF/MOSF             2
6                Coma             3

income mapping:
        income  income_enum
5          NaN           -1
1     $11-$25k            0
3   under $11k            1
7     $25-$50k            2
16       >$50k            3

race mapping:
         race  race_enum
259       NaN         -1
1       other          0
2       white          1
9       black          2
10   hispanic          3
24      asian          4

ca mapping

C:\Users\itsjo\AppData\Local\Temp\ipykernel_12372\1885369418.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_cols = df_clean.select_dtypes(include=['object']).columns
C:\Users\itsjo\AppData\Local\Temp\ipykernel_12372\1885369418.py:21: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  cat = pd.Categorical(df_clean[col], categories=category_orders[col], ordered=True)


In [15]:
target = 'no(M2 and SIP pres)'
raw_vals = df_raw['sfdm2'].dropna().unique()

for v in raw_vals:
    print(v == target, repr(v), repr(target))

False '<2 mo. follow-up' 'no(M2 and SIP pres)'
True 'no(M2 and SIP pres)' 'no(M2 and SIP pres)'
False 'SIP>=30' 'no(M2 and SIP pres)'
False 'adl>=4 (>=5 if sur)' 'no(M2 and SIP pres)'
False 'Coma or Intub' 'no(M2 and SIP pres)'


In [15]:
# scikit already assumes that any int columns are to be kept discrete if it has under 10 int values. 
# This is a check to see if any adjustments need to be made from the default settings.
for col in df_clean.columns:
    if col.endswith('_enum'):
        print(col, df_clean[col].nunique())

sex_enum 2
dzgroup_enum 8
dzclass_enum 4
income_enum 5
race_enum 6
ca_enum 3
dnr_enum 4
sfdm2_enum 5


In [16]:
# 'age' should not have any values under 18 and the likelihood of anyone being 115 is almost 0.

before = df_clean.shape[0]
df_clean = df_clean[(df_clean['age'] >= 18) & (df_clean['age'] <= 115)]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")

Rows removed: 0


In [17]:
# Whether they died is irrelevant to this study

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['death', 'hospdead'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 2


In [18]:
# 'sex' is a useful metric

before = df_clean.shape[0]
df_clean = df_clean[df_clean['sex_enum']!= -1]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")

Rows removed: 0


In [19]:
# 'slos' denotes number of days they were in hospital before being discharged.
# Point of data leakage. Feature to be removed.

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['slos'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 1


In [20]:
# 'd.time' denotes number of days patients were in the study. 
# If they didn't reach 2 months they didn't get an sfdm2 value.
# If they exceeded it then they got one and the variable is no longer relevant.
# We can remove the feature

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['d.time'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 1


In [21]:
# 'dzgroup' and 'dzclass' and 'num.co' denote disease types and numbers which will be very helpful.
# Nothing looks out of place.

In [22]:
# Many education level entries are missing. There is also an individual income column.
# We assumption that education level will not directly affect deterioration in terminally ill patients
# The whole column will simply be removed as its both difficult to average and of low importance.

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['edu'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 1


In [23]:
# Income feature is missing to many phenotypes

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['income_enum'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 1


In [24]:
# 'scoma' is a measure of how deep in a coma they are on a scale of 0 - 100.
# All values are in valid ranges but one entry is missing.

before = df_clean.shape[0]
df_clean = df_clean[df_clean['scoma'].notna()]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")

Rows removed: 1


In [25]:
# 'charges' denotes their number of hospital charges.
# This would include dates extended past day three. Data leakage point.
# Feature to be removed.

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['charges'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 1


In [26]:
# 'totcst', 'totmcst' are cost related iteams that are missing to many values.

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['totcst', 'totmcst'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 2


In [27]:
# 'avtisst' is a score related to amount of care required from days 3 to 25.
# We are trying make a prediction on day three so this is data leakage.
# Feature to be removed.

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['avtisst'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 1


In [28]:
# 'race' denotes as implied.
# Useful information, only a few entires missing, and looks clean based on TS1 scope.
# Will remove empty entries.

before = df_clean.shape[0]
df_clean = df_clean[df_clean['race_enum'] != -1]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")
print(f"Remaining rows: {after}")

Rows removed: 42
Remaining rows: 9062


In [29]:
# 'sps' and 'aps' are both physiological scores taken at day 3 that may be very useful
# 'sps' ranges from 0 to 163 and 'aps' ranges from 0 to 299, meaning all recorded values are within spec according to scoping in task 1.
# A few records are missing

before = df_clean.shape[0]
df_clean = df_clean[df_clean['sps'].notna()]
df_clean = df_clean[df_clean['aps'].notna()]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")

#These entries must have already been removed in a previous removal.

Rows removed: 0


In [30]:
# 'surv2m' and 'surv6m' is a machine's estimate of the patients odds of survival in 2 and 6 months time.
# This wont actually impact what condition they're in in 2 months so we will remove it entirely.

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['surv2m', 'surv6m'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 2


In [31]:
# 'hday' denotes the number of days the patient had already been in hospital before being diagnosed as terminally ill.
# This is useful as it tells us how long we have known them to be in this state.
# No entries missing and seems fine based on T1 scope.

In [32]:
# 'diabetes' and 'dementia' are as named and have binary values.
# Useful information with no cleaning required.

In [33]:
# 'ca' denotes cancer and has three potential values.
# Useful information
# No entries missing and seems fine based on T1 scope.

In [34]:
# As per 'surv2m' and 'surv6m', 'prg2m' and 'prg6m' are practitioners guesses at the well being of the patient in 2 and 6 months time.
# Will not effect actual outcome so will be removed.

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['prg2m', 'prg6m'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 2


In [35]:
# 'dnrday' marks day the DNR order was given.
# Our model is meant to function on information recieved in day three. Anything after this is seeing into the future.
# The large majority of instances have phenotypes within this feature exceeding 3 days, and therefore the feature is removed.

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['dnrday'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 1


In [36]:
# 'dnr' has to be removed due to the removal of dnr day. The order was probably given much after the 3 day mark.
before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['dnr_enum'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 1


In [37]:
# 'meanbp' is a blood pressure reading on day three. 
# Useful information but 1 record missing, and the minimum is recorded as 0, which is impossible.
# The maximum is very extreme, but these are terminally ill patients. 
# Extremely high and low blood pressures should not be instantly be deemed errors in this instance.

before = df_clean.shape[0]
df_clean = df_clean[(df_clean['meanbp'] != 0) & (df_clean['meanbp'].notna())]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")

Rows removed: 51


In [38]:
# 'wblc' is a white blood cell count measured in thousands on day 3.     
# Useful information but multiple records missing and more absurd values.
# There are records of very high white blood cell counts, but depending on the disease that might make sense.
# Further analysis showed that all cases of high wblc were tied to patients with diseaess knwon to cuase high wblc.
# This lead to the following action:

before = df_clean.shape[0]
df_clean = df_clean[(df_clean['wblc'] != 0) & (df_clean['wblc'].notna())]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")

Rows removed: 221


In [39]:
# 'hrt' refers to heart rate measured on day 3.
# Useful information but has readings from 0 to 300. Anything below 30 is practically implausible, so will be considered invalid.
# Will remove the NaN and <20 rows along with the 300 row before rechecking boundires.

before = df_clean.shape[0]

df_clean = df_clean[(df_clean['hrt'] >= 30) & (df_clean['hrt'].notna())]

# Remove the isolated 300 outlier
df_clean = df_clean[df_clean['hrt'] != 300]

after = df_clean.shape[0]
print(f"Rows removed: {before - after}")

# Recheck min and max
print("New min hrt:", df_clean['hrt'].min())
print("New max hrt:", df_clean['hrt'].max())

Rows removed: 54
New min hrt: 30.0
New max hrt: 250.0


In [40]:
# 'resp' is the resperation rate of the patient measured on day 3. 
# Useful information but one record marked as missing and more entries at 0.
# Any reocrds at a rate below 4 will be removed.
# 90 seems plausible so will be left as is. 

before = df_clean.shape[0]

df_clean = df_clean[df_clean['resp'] != 0]
df_clean = df_clean[df_clean['resp'] >= 4]

after = df_clean.shape[0]
print(f"Rows removed: {before - after}")
print(f"Remaining rows: {after}")

print("New min resp:", df_clean['resp'].min())
print("New max resp:", df_clean['resp'].max())

Rows removed: 20
Remaining rows: 8716
New min resp: 4.0
New max resp: 90.0


In [41]:
# 'temp' refers to body tempreture.
# Useful information that seems to land within bounds but is marked as missing one entry.

before = df_clean.shape[0]
df_clean = df_clean[(df_clean['temp'].notna())]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")

Rows removed: 0


In [42]:
# 'pafi', 'alb' and 'bili' are all simply missing to many rows to be used to have averages applied.
# All three were removed.

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['pafi', 'alb', 'bili'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")

Columns removed: 3


In [43]:
# 'crea' and 'sod' denote creatine and sodium levels measured on day 3. 
# Useful information with only a few missing entries.
# Unsure of what values here are reasonable but there are no zero entries so I will only remove NaN for now.

before = df_clean.shape[0]
df_clean = df_clean[(df_clean['crea'].notna())]
df_clean = df_clean[(df_clean['sod'].notna())]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")

Rows removed: 19


In [44]:
# Repeat of 'pafi', 'alb' and 'bili'
# 'ph', gluscose', 'bun', 'urine', 'adlp' and 'adls' all hope potentially useful information but are missing far too many records.
# All columns will be removed

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['ph', 'glucose', 'bun', 'urine', 'adlp', 'adls'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")    

Columns removed: 6


In [45]:
# 'sfdm2' is our target prediction feature. 
# Hence, while it is missing a lot of values, we can only use entires with this feature.
# All missing this feature will be removed.

before = df_clean.shape[0]
df_clean = df_clean[(df_clean['sfdm2_enum'] != -1)]
after = df_clean.shape[0]

print(f"Rows removed: {before - after}")

Rows removed: 4272


In [46]:
# 'adlsc' refers to a wellbeing measurement taken at the 2 month meetings that we are trying to predict.
# This means that it's data the mlm should not have access too when trying to train.
# Removing the column

before = df_clean.shape[1]
df_clean = df_clean.drop(columns=['adlsc'])
after = df_clean.shape[1]

print(f"Columns removed: {before - after}")   

Columns removed: 1


In [47]:
# Verifying changes made:

print("--- Missing values ---")
print(df_clean.isna().sum())  # Count of missing values per column

print("\n=== Data Types ===")
print(df_clean.dtypes)

print("--- Duplicate rows ---")
print(df_clean.duplicated().sum())  # Count of duplicate rows

print("--- Columns ---")
before = df_raw.shape[1]
after = df_clean.shape[1]
print(f"Originally: {before}")
print(f"Removed: {before - after}")
print(f"Remaining: {after}")

print("--- Rows ---")
before = df_raw.shape[0]
after = df_clean.shape[0]
print(f"Originally: {before}")
print(f"Removed: {before - after}")
print(f"Remaining: {after}")

--- Missing values ---
age             0
num.co          0
scoma           0
sps             0
aps             0
hday            0
diabetes        0
dementia        0
meanbp          0
wblc            0
hrt             0
resp            0
temp            0
crea            0
sod             0
sex_enum        0
dzgroup_enum    0
dzclass_enum    0
race_enum       0
ca_enum         0
sfdm2_enum      0
dtype: int64

=== Data Types ===
age             float64
num.co            int64
scoma           float64
sps             float64
aps             float64
hday              int64
diabetes          int64
dementia          int64
meanbp          float64
wblc            float64
hrt             float64
resp            float64
temp            float64
crea            float64
sod             float64
sex_enum          int64
dzgroup_enum      int64
dzclass_enum      int64
race_enum         int64
ca_enum           int64
sfdm2_enum         int8
dtype: object
--- Duplicate rows ---
0
--- Columns ---
Origina

## Task 4 - Novelity

This section will create a base model with our new clean dataframe and compare it to versions only missing the specific feature we want to test. 

This will be achieved through the following steps:
- A base model predicting sdfm2 with the current df_clean dataframe will be made utilising all features.
- This base model will be run at 10 set seeds, and ten f1 scores will be calculated.
- An additional indentical dataframe will be temporarily generated, but the singular feature we wish to test will be dropped.
- This temporary dataframe will be run with the same 10 seeds as the base model, and another 10 f1 scores will be generated.
- A p-score will be generated based on the difference between the base model and temporary models f1 scores.

This will:
- Give us a good idea of how much impact one feature has.
- Help reduce computation resources by not processing features that do not help with the overall predictions of the model.

In [48]:
# This chunk creates a tool set to evaluate the usefulness of an individual feature within the dataset
# It deletes the feature from the dataset, trains an eLCS model on the remaining features, and evaluates its performance.

def evaluate_elcs_variant(df, target_col, variant_name, random_state=42, test_size=0.20, **elcs_kwargs):
  
    X = df.drop(columns=[target_col]) # Drop the target column
    y = df[target_col]

    X_train, X_test, y_train, y_test = train_test_split( # Create the train/test split
        X, y,
        test_size=test_size,
        random_state=random_state,
        stratify=y,
    )

    model = eLCS(random_state=random_state, **elcs_kwargs) # Create the model
    model.fit(X_train.to_numpy(), y_train.to_numpy()) # Train the model

    y_pred = model.predict(X_test.to_numpy()) # Make a prediction with the model

    return {
        "variant": variant_name,
        "seed": random_state,
        "n_features": X.shape[1],
        "n_rules": len(model.population.popSet),
        "iterations": model.explorIter,
        "balanced_accuracy": balanced_accuracy_score(y_test, y_pred),
        "precision_macro": precision_score(y_test, y_pred, average="macro", zero_division=0),
        "recall_macro": recall_score(y_test, y_pred, average="macro", zero_division=0),
        "f1_macro": f1_score(y_test, y_pred, average="macro", zero_division=0),
    }

# The following function evaluates a specific variant of the eLCS model across multiple random seeds 
# This allows for a more robust assessment of the model's performance by averaging results over different data splits.

def evaluate_elcs_variant_multiseed(df, target_col, variant_name, seeds=range(5), test_size=0.20, **elcs_kwargs):
    
    return [
        evaluate_elcs_variant(df, target_col, variant_name, random_state=seed, test_size=test_size, **elcs_kwargs)
        for seed in seeds
    ]

# The following function summarizes the results of multiple runs of the eLCS model across different variants and seeds.

def summarize_runs(all_results):
   
    raw_df = pd.DataFrame(all_results)

    metric_cols = ["balanced_accuracy", "precision_macro", "recall_macro", "f1_macro", "n_rules", "iterations"]

    summary_df = raw_df.groupby("variant")[metric_cols].agg(["mean", "std"])
    summary_df.columns = [f"{metric}_{stat}" for metric, stat in summary_df.columns]
    summary_df = summary_df.reset_index()

    return raw_df, summary_df

In [49]:
# The following functions handle caching of results to avoid redundant computations when evaluating different variants of the eLCS model.
# New tests can be assigned a new name, and if no subsection of this csv exists under that name, it will be created. 
# If a test has already been run with that name and number of seeds then it will be skipped and the cached results will be used instead.
import os

RESULTS_PATH = "test_elcs_results.csv"

def load_cached_results():
    if os.path.exists(RESULTS_PATH):
        return pd.read_csv(RESULTS_PATH)
    return pd.DataFrame(columns=["variant", "seed"])  # empty cache

def save_results(raw_df):
    raw_df.to_csv(RESULTS_PATH, index=False)

def run_variant_if_missing(df, target_col, variant_name, seeds, **elcs_kwargs):
    cached = load_cached_results()
    already_done = set(cached.loc[cached["variant"] == variant_name, "seed"]) if not cached.empty else set()
    missing_seeds = [s for s in seeds if s not in already_done]

    if missing_seeds:
        print(f"Running {variant_name} for seeds {missing_seeds}...")
        new_results = evaluate_elcs_variant_multiseed(df, target_col, variant_name, seeds=missing_seeds, **elcs_kwargs)
        cached = pd.concat([cached, pd.DataFrame(new_results)], ignore_index=True)
        save_results(cached)
    else:
        print(f"{variant_name} already cached for all requested seeds — skipping.")

    return cached

In [50]:
# This chunk is designed to allow the creation of multifple new dataframes.
# Unfortunatley for our model, most p-values are pretty high, with only one feature having a p score below 5%.
# Because of this multiple new dataframes will be created, with each only including features falling under certain p-value threshholds. 
# This will simplify testing in the next phase, and allow us to identify via experimentation at what p-value features 
# become truely meaningless.
# A new dataframe will be created in every 10% inverval from 90 downwards.

# Create a dictionary for the new dataframes.
feature_p_values = {}

# Step 2: the function that builds a variant dataframe for a given threshold.
# A feature is DROPPED if its p-value is >= threshold (i.e. not "significant" at that level).
# A feature is KEPT if its p-value is < threshold.

# This function takes the dataframe to be filtered, the feature p-values, and the threshold.
# It returns a new dataframe with the appropriate features dropped.
# This wont be run until the end, when all dictionaries are created and the p-values are known.
def build_threshold_variant(df, feature_p_values, threshold):
    features_to_drop = [feat for feat, p in feature_p_values.items() if p is not None and p >= threshold]
    variant_df = df.drop(columns=features_to_drop, errors="ignore")
    print(f"Threshold {threshold}: dropping {len(features_to_drop)} feature(s) -> {features_to_drop}")
    return variant_df

In [51]:
# Create a new dataframe to create baseline model testing
df_testing = df_clean.copy()

# Obtain new data for the baseline set if it hasnt been run yet, otherwise load the cached results.
results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))

Running baseline (all features) for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...


In [52]:
# 'age' is the first remaining feature. This may be useful and has no reason to be removed outright.
from scipy.stats import ttest_rel

# Add to the data frame a new set of tests that exclude age if not already available in the cache.
results_so_far = run_variant_if_missing(df_testing.drop(columns=["age"]), "sfdm2_enum", "without age", seeds=range(10))

# Use the f1 macro to score the new base model resluts and new age-removed model results.
baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
age_f1 = results_so_far[results_so_far["variant"] == "without age"].sort_values("seed")["f1_macro"].values

# We now use the f1 scores to perform a paired t-test to determine if the difference 
# in performance between the two models is statistically significant.

# The t value is essentially a signal to noise ratio, 
# where the signal is the difference in means and the noise is the variability of the differences.
# Higher t values indicate a larger difference between the two models, implying that the feature is of high importance.

# The p value measures the consistency of the difference in performance across the different seeds. 
# If the p value is less than 0.05, then there is strong correlation between the f1 scores of the two models, 
# and we can conclude that the difference in performance is statistically significant.

t_stat, p_value = ttest_rel(baseline_f1, age_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

# Creation of dictionary entry for the creation of p-value threshold dataframes.
feature_p_values["age"] = p_value

Running without age for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 0.993, p = 0.3469


In [53]:
# Testing 'sex_enum'
results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["sex_enum"]), "sfdm2_enum", "without sex", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
sex_f1 = results_so_far[results_so_far["variant"] == "without sex"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, sex_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["sex_enum"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without sex for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 2.436, p = 0.0376


In [54]:
# Testing 'dzgroup'
results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["dzgroup_enum"]), "sfdm2_enum", "without dzgroup", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
dzgroup_f1 = results_so_far[results_so_far["variant"] == "without dzgroup"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, dzgroup_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["dzgroup_enum"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without dzgroup for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 0.707, p = 0.4976


In [55]:
# Testing 'dzclass':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["dzclass_enum"]), "sfdm2_enum", "without dzclass", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
dzclass_f1 = results_so_far[results_so_far["variant"] == "without dzclass"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, dzclass_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["dzclass_enum"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without dzclass for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 1.645, p = 0.1343


In [56]:
# Testing 'num.co':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["num.co"]), "sfdm2_enum", "without num.co", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
num_co_f1 = results_so_far[results_so_far["variant"] == "without num.co"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, num_co_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["num.co"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without num.co for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 2.912, p = 0.0172


In [57]:
# Testing 'scoma':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["scoma"]), "sfdm2_enum", "without scoma", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
scoma_f1 = results_so_far[results_so_far["variant"] == "without scoma"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, scoma_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["scoma"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without scoma for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 1.723, p = 0.1190


In [58]:
# Testing 'race':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["race_enum"]), "sfdm2_enum", "without race", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
race_f1 = results_so_far[results_so_far["variant"] == "without race"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, race_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["race_enum"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without race for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 2.089, p = 0.0663


In [59]:
# Testing 'sps':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["sps"]), "sfdm2_enum", "without sps", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
sps_f1 = results_so_far[results_so_far["variant"] == "without sps"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, sps_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["sps"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without sps for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 2.738, p = 0.0229


In [60]:
# Testing 'aps':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["aps"]), "sfdm2_enum", "without aps", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
aps_f1 = results_so_far[results_so_far["variant"] == "without aps"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, aps_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["aps"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without aps for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 1.352, p = 0.2094


In [61]:
# Testing 'hday':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["hday"]), "sfdm2_enum", "without hday", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
hday_f1 = results_so_far[results_so_far["variant"] == "without hday"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, hday_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["hday"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without hday for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 1.531, p = 0.1600


In [62]:
#Testing 'diabetes':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["diabetes"]), "sfdm2_enum", "without diabetes", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
diabetes_f1 = results_so_far[results_so_far["variant"] == "without diabetes"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, diabetes_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["diabetes"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without diabetes for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 1.939, p = 0.0845


In [63]:
#Testing 'dementia':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["dementia"]), "sfdm2_enum", "without dementia", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
dementia_f1 = results_so_far[results_so_far["variant"] == "without dementia"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, dementia_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["dementia"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without dementia for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 1.716, p = 0.1203


In [64]:
#Testing 'ca':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["ca_enum"]), "sfdm2_enum", "without cancer", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
cancer_f1 = results_so_far[results_so_far["variant"] == "without cancer"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, cancer_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["ca_enum"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without cancer for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 2.606, p = 0.0285


In [65]:
# Testing 'meanbp':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["meanbp"]), "sfdm2_enum", "without meanbp", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
meanbp_f1 = results_so_far[results_so_far["variant"] == "without meanbp"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, meanbp_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["meanbp"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without meanbp for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 0.918, p = 0.3827


In [66]:
# Testing 'wblc':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["wblc"]), "sfdm2_enum", "without wblc", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
wblc_f1 = results_so_far[results_so_far["variant"] == "without wblc"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, wblc_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["wblc"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without wblc for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 1.025, p = 0.3321


In [67]:
# Testing 'hrt':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["hrt"]), "sfdm2_enum", "without hrt", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
hrt_f1 = results_so_far[results_so_far["variant"] == "without hrt"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, hrt_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["hrt"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without hrt for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 0.790, p = 0.4499


In [68]:
# Testing 'resp':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["resp"]), "sfdm2_enum", "without resp", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
resp_f1 = results_so_far[results_so_far["variant"] == "without resp"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, resp_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["resp"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without resp for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = -0.338, p = 0.7430


In [69]:
# Testing 'temp':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["temp"]), "sfdm2_enum", "without temp", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
temp_f1 = results_so_far[results_so_far["variant"] == "without temp"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, temp_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["temp"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without temp for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 0.029, p = 0.9778


In [70]:
# Testing relevance of 'crea':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["crea"]), "sfdm2_enum", "without crea", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
crea_f1 = results_so_far[results_so_far["variant"] == "without crea"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, crea_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["crea"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without crea for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 0.880, p = 0.4018


In [71]:
# Testing relevance of 'sod':

results_so_far = run_variant_if_missing(df_testing, "sfdm2_enum", "baseline (all features)", seeds=range(10))
results_so_far = run_variant_if_missing(df_testing.drop(columns=["sod"]), "sfdm2_enum", "without sodium", seeds=range(10))

baseline_f1 = results_so_far[results_so_far["variant"] == "baseline (all features)"].sort_values("seed")["f1_macro"].values
sod_f1 = results_so_far[results_so_far["variant"] == "without sodium"].sort_values("seed")["f1_macro"].values

t_stat, p_value = ttest_rel(baseline_f1, sod_f1)
print(f"t = {t_stat:.3f}, p = {p_value:.4f}")

feature_p_values["sod"] = p_value

baseline (all features) already cached for all requested seeds — skipping.
Running without sodium for seeds [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
t = 1.704, p = 0.1225


In [72]:
# This chunk defines the thresholds and runs a loop to create new dataframes.

thresholds = [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
df_variants = {t: build_threshold_variant(df_clean, feature_p_values, t) for t in thresholds}

target_col = "sfdm2_enum"

for threshold, variant_df in df_variants.items():
    features = [col for col in variant_df.columns if col != target_col]
    print()
    print(f"df_clean_{threshold}")
    print(f"  Number of features: {len(features)}")
    print(f"  Features: {features}")

Threshold 0.9: dropping 1 feature(s) -> ['temp']
Threshold 0.8: dropping 1 feature(s) -> ['temp']
Threshold 0.7: dropping 2 feature(s) -> ['resp', 'temp']
Threshold 0.6: dropping 2 feature(s) -> ['resp', 'temp']
Threshold 0.5: dropping 2 feature(s) -> ['resp', 'temp']
Threshold 0.4: dropping 5 feature(s) -> ['dzgroup_enum', 'hrt', 'resp', 'temp', 'crea']
Threshold 0.3: dropping 8 feature(s) -> ['age', 'dzgroup_enum', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'crea']
Threshold 0.2: dropping 9 feature(s) -> ['age', 'dzgroup_enum', 'aps', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'crea']
Threshold 0.1: dropping 14 feature(s) -> ['age', 'dzgroup_enum', 'dzclass_enum', 'scoma', 'aps', 'hday', 'dementia', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'crea', 'sod']

df_clean_0.9
  Number of features: 19
  Features: ['age', 'num.co', 'scoma', 'sps', 'aps', 'hday', 'diabetes', 'dementia', 'meanbp', 'wblc', 'hrt', 'resp', 'crea', 'sod', 'sex_enum', 'dzgroup_enum', 'dzclass_enum', 'race_enum', 'ca_enum

## Task 5 - Experiments

Hoi Delululu

If you have a quick read through my comments in the previous section you will see I've left you a pile of new dataframes to experiment with. No feel obligated to use them all, they're just there for the sake of options.

They're all stored within a dictionary, so to acessing them is slightly different.
If you want the 80% threshold you'd use 'df_variants[0.8]' for example.

You can also change the list of thresholds within the last chunk if you want to change them at all. You shouldn't have to run any chunks again besides that one :)

I'll leave the following chunks there to make your life easier. They were previously in task 3 but they arnt as relevant to my sections as they will be to yours. 

You've also got the option to experiment with creating synthetic data based on the data we already have to help with the outcome skew. 
If you want to explore that option then the library 'imblearn' is already used within this notebook and has some pre-built functions you could ask a LLM about.

I'm almost certain they've mentioned having to try multiple different kinds of MLM's in class as well but cant see where it is on our task list? I assume it would fall under yours but maybe look into it?

Godspeed helldiver



In [73]:
# Updates the split in training and testing data 

X = df_clean.drop(columns=['sfdm2_enum'])   
y = df_clean['sfdm2_enum']   

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [74]:
# Checking how bad the imbalance is on the new data frame

print(y_train.value_counts())
print(y_train.value_counts(normalize=True) * 100)

sfdm2_enum
4    2368
1     713
2     428
3      31
Name: count, dtype: int64
sfdm2_enum
4    66.892655
1    20.141243
2    12.090395
3     0.875706
Name: proportion, dtype: float64


In [76]:
print(y_train.value_counts().sort_index())

sfdm2_enum
1     713
2     428
3      31
4    2368
Name: count, dtype: int64


In [75]:
# Capping counts at 1000 to reduce imbalance.

from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(sampling_strategy={0: 1000, 1: 1000}, random_state=42)
X_train_res, y_train_res = rus.fit_resample(X_train, y_train)

ValueError: The {0} target class is/are not present in the data.

In [ ]:
print(y_train.value_counts())       # before
print(pd.Series(y_train_res).value_counts())  # after — should now be equal counts

sfdm2_enum
0    2368
1    2358
3     713
2     428
4      31
Name: count, dtype: int64
sfdm2_enum
0    1000
1    1000
3     713
2     428
4      31
Name: count, dtype: int64


There is still a very significant imbalance in this data. It may be worth synthesising some data for rarer cases to help balance the odds? Keen to hear yall's thoughts on this. 

In [ ]:
# Helldiver is now here, task 5 will be exterminated

# Going through the cons and pros of each training method - 80/20 and k-fold cross validation.
# 80/20 is a simple split, and ideally good for large data-sets. However because there is a large imbalance in our data-set the k-fold cross validation may be a better option.
# with k-fold cross validation we'll be training the model with k-1 folds, and testing it on the remaining fold, this can give up a more reliable performance of the model.
# as our data-set is not very large after cleeaning, the k-fold cross validation will be used and will also make each person only being tested once.


from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.metrics import balanced_accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, accuracy_score

# Creating a function to evaluate the model for k-fold cross validation

def train_and_evaluate_model(x, y, model, k = 5): #k = 5 is chosen as there is a large imbalance in the data-set, so to ensure there is relatively good representation for each class k = 5 is initially kept

    K_fold = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)

    #evaluation parameters
    balanced_accuracy = []
    macro_precision = []
    macro_recall = []
    macro_f1 = []
    accuracy = []
    all_actual = []
    all_predicted = []

    #training the model and evaluating each fold

    for train_index, test_index in K_fold.split(x, y):

        x_train, x_test = x.iloc[train_index], x.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        fold_model = clone(model)  #New model for each fold and allows indepenent training for each fold

        fold_model.fit(x_train.to_numpy(), y_train.to_numpy())
        y_pred = fold_model.predict(x_test.to_numpy())

        balanced_accuracy.append(balanced_accuracy_score(y_test, y_pred))
        macro_precision.append(precision_score(y_test, y_pred, average='macro', zero_division=0))
        macro_recall.append(recall_score(y_test, y_pred, average='macro', zero_division=0))
        macro_f1.append(f1_score(y_test, y_pred, average='macro', zero_division=0))
        accuracy.append(accuracy_score(y_test, y_pred))
        all_actual.extend(y_test)
        all_predicted.extend(y_pred)

        results = {
            "Balanced Accuracy": balanced_accuracy,
                    "Macro Precision": macro_precision,
                    "Macro Recall": macro_recall,
                    "Macro F1": macro_f1,
                    "Accuracy": accuracy,
        }

    return results, confusion_matrix(all_actual, all_predicted)
        


In [ ]:
#First training and testing of the eLCS model with k-fold cross validation

#training original model with k-fold cross validation

x_original = df_clean.drop(columns=['sfdm2_enum']) 
y_original = df_clean['sfdm2_enum']

original_model_training, original_matrix = train_and_evaluate_model(x_original, y_original, baseline_elcs, k = 5)

results_of_original_model = pd.DataFrame(original_model_training)

print("Results of the original model with k-fold cross validation:")
print(results_of_original_model.describe())
print("Confusion Matrix of the original model:")
print(original_matrix)

Results of the original model with k-fold cross validation:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.298273         0.369286      0.298273  0.268934  0.594058
std             0.004318         0.083860      0.004318  0.004988  0.007618
min             0.293227         0.276924      0.293227  0.264279  0.584125
25%             0.295776         0.281894      0.295776  0.264564  0.590909
50%             0.298063         0.402003      0.298063  0.269012  0.592542
75%             0.299625         0.436397      0.299625  0.270344  0.598644
max             0.304678         0.449211      0.304678  0.276468  0.604068
Confusion Matrix of the original model:
[[2154  783   16    7    0]
 [ 713 2216   13    6    0]
 [ 173  361    1    0    0]
 [ 451  425    6    9    0]
 [  29    9    1    0    0]]


In [ ]:
#training the model with p thresholds, starting with threshold 0.9, and will continue down to 0.1

x_zeroNine = df_variants[0.9].drop(columns=['sfdm2_enum'])
y_zeroNine = df_variants[0.9]['sfdm2_enum']

zeroNine_model_training, zeroNine_confusion_matrix = train_and_evaluate_model(x_zeroNine, y_zeroNine, baseline_elcs, k = 5)

results_of_zeroNine_model = pd.DataFrame(zeroNine_model_training)
print("Results of the model with p of 0.9 threshold:")
print(results_of_zeroNine_model.describe())
print("Confusion Matrix of the model with p of 0.9 threshold:")
print(zeroNine_confusion_matrix)


Results of the model with p of 0.9 threshold:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.298826         0.296655      0.298826  0.269712  0.594197
std             0.004886         0.045905      0.004886  0.005469  0.011057
min             0.293630         0.244976      0.293630  0.263436  0.585085
25%             0.294312         0.268158      0.294312  0.264411  0.586441
50%             0.299477         0.287878      0.299477  0.271558  0.588874
75%             0.301527         0.319764      0.301527  0.273740  0.599322
max             0.305183         0.362498      0.305183  0.275414  0.611262
Confusion Matrix of the model with p of 0.9 threshold:
[[2045  903    6    6    0]
 [ 602 2324   14    8    0]
 [ 129  403    2    1    0]
 [ 424  454    3   10    0]
 [  30    9    0    0    0]]


In [ ]:
#now training for dataset from p threshold of 0.8

x_zeroEight = df_variants[0.8].drop(columns=['sfdm2_enum'])
y_zeroEight = df_variants[0.8]['sfdm2_enum']

zeroEight_model_training, zeroEight_confusion_matrix = train_and_evaluate_model(x_zeroEight, y_zeroEight, baseline_elcs, k = 5)

results_of_zeroEight_model = pd.DataFrame(zeroEight_model_training)
print("Results of the model with p of 0.8 threshold:")
print(results_of_zeroEight_model.describe())
print("Confusion Matrix of the model with p of 0.8 threshold:")
print(zeroEight_confusion_matrix)

Results of the model with p of 0.8 threshold:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.297386         0.276314      0.297386  0.267532  0.592839
std             0.005066         0.056498      0.005066  0.003379  0.012863
min             0.291389         0.239773      0.291389  0.263089  0.574237
25%             0.293151         0.242960      0.293151  0.265652  0.585482
50%             0.297794         0.259379      0.297794  0.268274  0.596610
75%             0.301891         0.263767      0.301891  0.268552  0.603121
max             0.302706         0.375692      0.302706  0.272092  0.604746
Confusion Matrix of the model with p of 0.8 threshold:
[[2060  874    3   23    0]
 [ 618 2302    3   25    0]
 [ 144  384    0    7    0]
 [ 423  458    0    9    1]
 [  30    9    0    0    0]]


In [ ]:
#training with p threshold of 0.7

x_zeroSeven = df_variants[0.7].drop(columns=['sfdm2_enum'])
y_zeroSeven = df_variants[0.7]['sfdm2_enum']

zeroSeven_model_training, zeroSeven_confusion_matrix = train_and_evaluate_model(x_zeroSeven, y_zeroSeven, baseline_elcs, k = 5)

results_of_zeroSeven_model = pd.DataFrame(zeroSeven_model_training)
print("Results of the model with p of 0.7 threshold:")
print(results_of_zeroSeven_model.describe())
print("Confusion Matrix of the model with p of 0.7 threshold:")
print(zeroSeven_confusion_matrix)

Results of the model with p of 0.7 threshold:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.295719         0.265198      0.295719  0.264884  0.590805
std             0.005872         0.041109      0.005872  0.004335  0.013307
min             0.291373         0.234340      0.291373  0.259736  0.578983
25%             0.291545         0.241862      0.291545  0.261932  0.580733
50%             0.291689         0.243871      0.291689  0.264463  0.584407
75%             0.300171         0.271681      0.300171  0.267824  0.601356
max             0.303815         0.334235      0.303815  0.270463  0.608548
Confusion Matrix of the model with p of 0.7 threshold:
[[2108  832    7   13    0]
 [ 686 2244    8   10    0]
 [ 146  387    1    1    0]
 [ 446  442    0    3    0]
 [  31    8    0    0    0]]


In [ ]:
#training for dataset from p threshold of 0.6

x_zeroSix = df_variants[0.6].drop(columns=['sfdm2_enum'])
y_zeroSix = df_variants[0.6]['sfdm2_enum']

zeroSix_model_training, zeroSix_confusion_matrix = train_and_evaluate_model(x_zeroSix, y_zeroSix, baseline_elcs, k = 5)

results_of_zeroSix_model = pd.DataFrame(zeroSix_model_training)
print("Results of the model with p of 0.6 threshold:")
print(results_of_zeroSix_model.describe())
print("Confusion Matrix of the model with p of 0.6 threshold:")
print(zeroSix_confusion_matrix)

Results of the model with p of 0.6 threshold:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.293739         0.257464      0.293739  0.263351  0.585923
std             0.005259         0.018930      0.005259  0.003586  0.012588
min             0.288793         0.238801      0.288793  0.259033  0.575593
25%             0.290547         0.242670      0.290547  0.261273  0.576949
50%             0.291091         0.254624      0.291091  0.263768  0.578697
75%             0.296812         0.265628      0.296812  0.264061  0.594576
max             0.301453         0.285599      0.301453  0.268622  0.603799
Confusion Matrix of the model with p of 0.6 threshold:
[[2087  857   11    5    0]
 [ 707 2228    9    4    0]
 [ 151  381    3    0    0]
 [ 440  445    4    2    0]
 [  31    8    0    0    0]]


In [ ]:
#training for dataset from p threshold of 0.5

x_zeroFive = df_variants[0.5].drop(columns=['sfdm2_enum'])
y_zeroFive = df_variants[0.5]['sfdm2_enum']

zeroFive_model_training, zeroFive_confusion_matrix = train_and_evaluate_model(x_zeroFive, y_zeroFive, baseline_elcs, k = 5)

results_of_zeroFive_model = pd.DataFrame(zeroFive_model_training)
print("Results of the model with p of 0.5 threshold:")
print(results_of_zeroFive_model.describe())
print("Confusion Matrix of the model with p of 0.5 threshold:")
print(zeroFive_confusion_matrix)

Results of the model with p of 0.5 threshold:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.289618         0.234879      0.289618  0.257229  0.580090
std             0.005253         0.001927      0.005253  0.005340  0.010587
min             0.280987         0.232850      0.280987  0.248229  0.562712
25%             0.288624         0.234032      0.288624  0.256668  0.578019
50%             0.291956         0.234074      0.291956  0.259784  0.584803
75%             0.292057         0.235581      0.292057  0.259822  0.585085
max             0.294465         0.237859      0.294465  0.261642  0.589831
Confusion Matrix of the model with p of 0.5 threshold:
[[1966  994    0    0    0]
 [ 637 2311    0    0    0]
 [ 143  392    0    0    0]
 [ 421  470    0    0    0]
 [  31    8    0    0    0]]


In [ ]:
#training for dataset from p threshold of 0.4

x_zeroFour = df_variants[0.4].drop(columns=['sfdm2_enum'])
y_zeroFour = df_variants[0.4]['sfdm2_enum']

zeroFour_model_training, zeroFour_confusion_matrix = train_and_evaluate_model(x_zeroFour, y_zeroFour, baseline_elcs, k = 5)
results_of_zeroFour_model = pd.DataFrame(zeroFour_model_training)
print("Results of the model with p of 0.4 threshold:")
print(results_of_zeroFour_model.describe())
print("Confusion Matrix of the model with p of 0.4 threshold:")
print(zeroFour_confusion_matrix)

Results of the model with p of 0.4 threshold:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.289618         0.234879      0.289618  0.257229  0.580090
std             0.005253         0.001927      0.005253  0.005340  0.010587
min             0.280987         0.232850      0.280987  0.248229  0.562712
25%             0.288624         0.234032      0.288624  0.256668  0.578019
50%             0.291956         0.234074      0.291956  0.259784  0.584803
75%             0.292057         0.235581      0.292057  0.259822  0.585085
max             0.294465         0.237859      0.294465  0.261642  0.589831
Confusion Matrix of the model with p of 0.4 threshold:
[[1966  994    0    0    0]
 [ 637 2311    0    0    0]
 [ 143  392    0    0    0]
 [ 421  470    0    0    0]
 [  31    8    0    0    0]]


In [ ]:
#training for dataset from p threshold of 0.3

x_zeroThree = df_variants[0.3].drop(columns=['sfdm2_enum'])
y_zeroThree = df_variants[0.3]['sfdm2_enum']

zeroThree_model_training, zeroThree_confusion_matrix = train_and_evaluate_model(x_zeroThree, y_zeroThree, baseline_elcs, k = 5)
results_of_zeroThree_model = pd.DataFrame(zeroThree_model_training)
print("Results of the model with p of 0.3 threshold:")
print(results_of_zeroThree_model.describe())
print("Confusion Matrix of the model with p of 0.3 threshold:")
print(zeroThree_confusion_matrix)

Results of the model with p of 0.3 threshold:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.285365         0.239499      0.285365  0.251997  0.571412
std             0.006925         0.003553      0.006925  0.007079  0.013859
min             0.273568         0.235030      0.273568  0.240172  0.547797
25%             0.285399         0.236440      0.285399  0.251655  0.571525
50%             0.288096         0.241120      0.288096  0.254611  0.576949
75%             0.288400         0.241721      0.288400  0.254765  0.577341
max             0.291365         0.243185      0.291365  0.258781  0.583446
Confusion Matrix of the model with p of 0.3 threshold:
[[1646 1314    0    0    0]
 [ 381 2567    0    0    0]
 [  86  449    0    0    0]
 [ 306  585    0    0    0]
 [  26   13    0    0    0]]


In [ ]:
#training for dataset from p threshold of 0.2

x_zeroTwo = df_variants[0.2].drop(columns=['sfdm2_enum'])
y_zeroTwo = df_variants[0.2]['sfdm2_enum']

zeroTwo_model_training, zeroTwo_confusion_matrix = train_and_evaluate_model(x_zeroTwo, y_zeroTwo, baseline_elcs, k = 5)
results_of_zeroTwo_model = pd.DataFrame(zeroTwo_model_training)
print("Results of the model with p of 0.2 threshold:")
print(results_of_zeroTwo_model.describe())
print("Confusion Matrix of the model with p of 0.2 threshold:")
print(zeroTwo_confusion_matrix)

Results of the model with p of 0.2 threshold:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.260073         0.230543      0.260073  0.222214  0.520550
std             0.004909         0.003174      0.004909  0.006399  0.009759
min             0.253669         0.226417      0.253669  0.214075  0.507797
25%             0.257389         0.228990      0.257389  0.218176  0.515254
50%             0.261069         0.230387      0.261069  0.223453  0.522388
75%             0.261432         0.232076      0.261432  0.224528  0.523390
max             0.266806         0.234843      0.266806  0.230837  0.533921
Confusion Matrix of the model with p of 0.2 threshold:
[[1113 1847    0    0    0]
 [ 223 2725    0    0    0]
 [  53  482    0    0    0]
 [ 230  661    0    0    0]
 [  24   15    0    0    0]]


In [ ]:
#training for dataset from p threshold of 0.1

x_zeroOne = df_variants[0.1].drop(columns=['sfdm2_enum'])
y_zeroOne = df_variants[0.1]['sfdm2_enum']

zeroOne_model_training, zeroOne_confusion_matrix = train_and_evaluate_model(x_zeroOne, y_zeroOne, baseline_elcs, k = 5)
results_of_zeroOne_model = pd.DataFrame(zeroOne_model_training)
print("Results of the model with p of 0.1 threshold:")
print(results_of_zeroOne_model.describe())
print("Confusion Matrix of the model with p of 0.1 threshold:")
print(zeroOne_confusion_matrix)

Results of the model with p of 0.1 threshold:
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.262477         0.227382      0.262477  0.226138  0.525435
std             0.007847         0.004037      0.007847  0.010951  0.015705
min             0.253669         0.221720      0.253669  0.214075  0.507797
25%             0.257389         0.226310      0.257389  0.218176  0.515254
50%             0.261432         0.226417      0.261432  0.224528  0.523390
75%             0.266067         0.230387      0.266067  0.232822  0.532564
max             0.273828         0.232076      0.273828  0.241088  0.548168
Confusion Matrix of the model with p of 0.1 threshold:
[[1232 1728    0    0    0]
 [ 306 2642    0    0    0]
 [  68  467    0    0    0]
 [ 276  615    0    0    0]
 [  24   15    0    0    0]]


# Task 6: Model Comparison - Chris
#### 6.1 Original LCS on Raw/Minimally processed environment 
#### 6.2 Original LCS on the preprocessed dataset
#### 6.3 Improved LCS-based system on the preprocessed and/or feature-engineered dataset.
#### 6.4 At least three conventional non-deep-learning machine learning models. 


In [ ]:
# I'll make and run 3 MLM first and then do the comparison of the results. 

In [ ]:
# 1st will be the Random Forest MLM. This model works best with medium to large datasets containing nonlinear, and complex relationships. 
# it works fine with mixed data types, and is robust to outliers and noise. It can also handle missing values, and is less prone to overfitting than other models.

# Import the Random Forest classifier.
from sklearn.ensemble import RandomForestClassifier

# Separate the cleaned predictors from the target.
X_rf = df_clean.drop(columns=["sfdm2_enum"])
y_rf = df_clean["sfdm2_enum"]

# Create the Random Forest model.
# random_state makes the experiment reproducible.
# n_jobs=-1 uses all available CPU cores; it does not change the model logic.
rf_model = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

# Evaluate Random Forest using the same 5-fold stratified CV used for eLCS.
rf_training, rf_confusion_matrix = train_and_evaluate_model(
    X_rf,
    y_rf,
    rf_model,
    k=5
)

# Convert the fold results into a dataframe.
rf_results = pd.DataFrame(rf_training)

# Display the results.
print("Random Forest - 5-Fold Cross-Validation")
print(rf_results.describe())

print("\nRandom Forest Confusion Matrix:")
print(rf_confusion_matrix)



Random Forest - 5-Fold Cross-Validation
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.310560         0.316026      0.310560  0.283158  0.614269
std             0.004037         0.009158      0.004037  0.005034  0.006724
min             0.305020         0.305217      0.305020  0.277129  0.604746
25%             0.308972         0.307426      0.308972  0.280528  0.612619
50%             0.309866         0.319020      0.309866  0.282599  0.612881
75%             0.313803         0.323518      0.313803  0.284999  0.618725
max             0.315139         0.324947      0.315139  0.290534  0.622373

Random Forest Confusion Matrix:
[[2233  704    1   22    0]
 [ 660 2271    0   17    0]
 [ 150  377    0    8    0]
 [ 444  422    0   25    0]
 [  31    8    0    0    0]]


In [ ]:
 # 2nd will be the Decision Tree MLM. This model is easy to understand and interpret, and can handle both numerical and categorical data. 
 # It can capture nonlinear relationships, and is robust to outliers. However, it can be prone to overfitting, especially with small datasets.

# Import the Decision Tree classifier.
from sklearn.tree import DecisionTreeClassifier

# Separate predictors from the target.
X_dt = df_clean.drop(columns=["sfdm2_enum"])
y_dt = df_clean["sfdm2_enum"]

# Create the Decision Tree model.
# random_state makes the model reproducible.
dt_model = DecisionTreeClassifier(
    random_state=42
)

# Evaluate it using the same 5-fold stratified CV function
# already used for the eLCS and Random Forest.
dt_training, dt_confusion_matrix = train_and_evaluate_model(
    X_dt,
    y_dt,
    dt_model,
    k=5
)

# Convert fold results into a dataframe.
dt_results = pd.DataFrame(dt_training)

# Display the results.
print("Decision Tree - 5-Fold Cross-Validation")
print(dt_results.describe())

print("\nDecision Tree Confusion Matrix:")
print(dt_confusion_matrix)


Decision Tree - 5-Fold Cross-Validation
       Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
count           5.000000         5.000000      5.000000  5.000000  5.000000
mean            0.273454         0.273934      0.273454  0.273355  0.462091
std             0.007981         0.006740      0.007981  0.007473  0.014129
min             0.265302         0.267318      0.265302  0.265939  0.446780
25%             0.267985         0.269064      0.267985  0.267843  0.452510
50%             0.271849         0.273046      0.271849  0.272150  0.458983
75%             0.276598         0.275829      0.276598  0.276139  0.470149
max             0.285536         0.284415      0.285536  0.284703  0.482034

Decision Tree Confusion Matrix:
[[1663  709  170  387   31]
 [ 745 1531  298  369    5]
 [ 155  246   63   70    1]
 [ 333  330   71  150    7]
 [  20    9    1    9    0]]


In [ ]:
# 3rd will be the Logistic Regression MLM. This model is simple and interpretable
# and works well for binary classification problems.

# however there are two main differences from the tree models. 
# Numerical features should be standardized to comparable scales, 
# and categorical features should be one-hot encoded.
# we are currently using 5-fold CV due to the class imbalances so we will retain that same validation method for this model.
  
# Imports required for preprocessing, modelling and evaluation.
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# Separate predictors and target.
X_lr = df_clean.drop(columns=["sfdm2_enum"])
y_lr = df_clean["sfdm2_enum"]

# Identify nominal categorical features.
# These variables contain category labels encoded as numbers.
# They should NOT be treated as continuous numerical quantities.
categorical_features = [
    "sex_enum",
    "dzgroup_enum",
    "dzclass_enum",
    "race_enum",
    "ca_enum"
] # what are these? these values are labels, pretending to be numbers, but they are not continuous 
# or meaningful numeric values.

# Everything else is treated as numerical.
# This includes continuous measurements and meaningful numeric counts/scores.
numeric_features = [
    col for col in X_lr.columns
    if col not in categorical_features
]

# Build preprocessing for Logistic Regression.
# Numerical: StandardScaler transforms features to approximately comparable scales.
# Categorical: OneHotEncoder creates separate binary columns for each category.
# drop="first" avoids redundant dummy columns.
# handle_unknown="ignore" prevents failure if a fold encounters a category not present in its training portion.
lr_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            StandardScaler(),
            numeric_features
        ),
        (
            "categorical",
            OneHotEncoder(
                drop="first",
                handle_unknown="ignore"
            ),
            categorical_features
        )
    ]
)
# OneHotEncoder. Why? A normal numerical model considers 4 > 3 > 2 > 1. Which is fine, but doesn't make sense for data such as race. 
# OneHotEncoder. How? it turns each category into a separate feature, and it becomes an independent binary feature. This way 
# the model can learn the importance of each category independently, and not assume that one is greater than another.
# if that is the case, why dont we use OneHotEncoder for all categorical features?
#  Because some categorical features are ordinal, meaning that they have a natural order. 
# For example, dzclass_enum has a natural order of severity, and it makes sense to treat 
# it as a numerical feature. However, race_enum does not have a natural order, and it 
# does not make sense to treat it as a numerical feature. Therefore, we use 
# OneHotEncoder for race_enum, but not for dzclass_enum.
# ...okay, why not one hot encode num.co? because num.co actually is a count. 

# why use standard scaler? our numerical features have varying numerical ranges. LR learns co-efficients, scaling 
# applies an equation to the features to make them comparable, so that one numerically large feature doesnt dominate. 
# this is similar to what we did for lab 1/2 whichever had the penguins, their bills were in mm while other measurements were in 
# cm so we scaled them to be comparable. 

# Create the Logistic Regression classifier.
# class_weight="balanced" automatically gives greater importance
# to rarer target classes.
# C=1.0 controls regularisation strength.
# Smaller C = stronger regularisation.
# max_iter is increased to make convergence more reliable.
# lbfgs supports multiclass Logistic Regression.
lr_classifier = LogisticRegression(
    solver="lbfgs",
    C=1.0,
    class_weight="balanced",
    max_iter=5000
)

# Combine preprocessing and classifier into one pipeline.
# This is important because preprocessing is fitted separately
# inside every training fold, preventing data leakage.
lr_model = Pipeline(
    steps=[
        ("preprocessing", lr_preprocessor),
        ("classifier", lr_classifier)
    ]
)
# what is this pipline? essentially what it does, in order: every fold:
# 1. training fold >
# 2. learn scaling values > 
# 3. learn categry encoding > 
# 4. train logistic regression > 
# 5. apply the SAME transformation to the test fold > 
# 6. predict the test fold. 

# Create stratified 5-fold cross-validation.
# Stratification keeps approximately the same target-class
# proportions in each fold.
lr_kfold = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Prepare storage for evaluation results.
lr_fold_results = []
lr_all_actual = []
lr_all_predicted = []

#Train and test Logistic Regression across all five folds.
for fold, (train_index, test_index) in enumerate(
    lr_kfold.split(X_lr, y_lr),
    start=1
):
    # Separate this fold's training and testing data.
    X_train_lr = X_lr.iloc[train_index]
    X_test_lr = X_lr.iloc[test_index]
    y_train_lr = y_lr.iloc[train_index]
    y_test_lr = y_lr.iloc[test_index]
    # Fit preprocessing and Logistic Regression
    # using ONLY the training fold.
    lr_model.fit(
        X_train_lr,
        y_train_lr
    )
    # Predict the classes of the untouched test fold.
    y_pred_lr = lr_model.predict(
        X_test_lr
    )
    # Calculate the same metrics used for the other models.
    lr_fold_results.append({
        "Fold": fold,
        "Balanced Accuracy":
            balanced_accuracy_score(
                y_test_lr,
                y_pred_lr
            ),
        "Macro Precision":
            precision_score(
                y_test_lr,
                y_pred_lr,
                average="macro",
                zero_division=0
            ),
        "Macro Recall":
            recall_score(
                y_test_lr,
                y_pred_lr,
                average="macro",
                zero_division=0
            ),
        "Macro F1":
            f1_score(
                y_test_lr,
                y_pred_lr,
                average="macro",
                zero_division=0
            ),
        "Accuracy":
            accuracy_score(
                y_test_lr,
                y_pred_lr
            )
    })
    # Store predictions from every fold for one final confusion matrix.
    lr_all_actual.extend(y_test_lr)
    lr_all_predicted.extend(y_pred_lr)

# Convert fold results into a dataframe.
lr_results = pd.DataFrame(
    lr_fold_results
)

# Build one confusion matrix from all out-of-fold predictions.
lr_confusion_matrix = confusion_matrix(
    lr_all_actual,
    lr_all_predicted
)

#Display individual fold results.
print("Logistic Regression - 5-Fold Cross-Validation")
print(lr_results)

#Display summary statistics.
print("\nLogistic Regression Summary:")
print(lr_results.describe())

#Display mean performance for easy Task 6 comparison.
print("\nMean Metrics:")
print(
    lr_results
    .drop(columns=["Fold"])
    .mean()
)

#Display combined confusion matrix.
print("\nLogistic Regression Confusion Matrix:")
print(lr_confusion_matrix)

Logistic Regression - 5-Fold Cross-Validation
   Fold  Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Accuracy
0     1           0.357696         0.355723      0.357696  0.314314  0.427119
1     2           0.410131         0.355807      0.410131  0.318603  0.428475
2     3           0.353568         0.334935      0.353568  0.294040  0.403390
3     4           0.406011         0.359186      0.406011  0.322907  0.433514
4     5           0.373409         0.347561      0.373409  0.310913  0.426052

Logistic Regression Summary:
           Fold  Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  \
count  5.000000           5.000000         5.000000      5.000000  5.000000   
mean   3.000000           0.380163         0.350642      0.380163  0.312155   
std    1.581139           0.026570         0.009769      0.026570  0.011086   
min    1.000000           0.353568         0.334935      0.353568  0.294040   
25%    2.000000           0.357696         0.347561      0.35

In [ ]:
# ORIGINAL LCS ON RAW DATA - Bring in the Task 2 result; this model used one 80/20 test split.
# Run the Task 2 result cell first so baseline_results exists.
raw_lcs_scores = baseline_results.set_index("Metric")["Value"].astype(float)

raw_lcs_row = {
    "Model": "Original eLCS — raw data",
    "Validation": "80/20 split",
    "Accuracy": raw_lcs_scores["Accuracy"],
    "Balanced Accuracy": raw_lcs_scores["Balanced Accuracy"],
    "Macro Precision": raw_lcs_scores["Macro Precision"],
    "Macro Recall": raw_lcs_scores["Macro Recall"],
    "Macro F1": raw_lcs_scores["Macro F1"],
}

In [ ]:
# TWO LCS RUNS ON CLEANED DATA Bring in the five-fold results already calculated in cells 83 and 84.
# The 0.9 threshold is your feature-selected LCS candidate.
clean_lcs_results = results_of_original_model
feature_selected_lcs_results = results_of_zeroNine_model

In [ ]:
# COMPARISON WITH CONVENTIONAL MLMS All models here except the raw eLCS used five-fold cross-validation.
# Their five fold scores are averaged to make one row per model.
cv_models = {
    "Original eLCS — cleaned data": clean_lcs_results,
    "Feature-selected eLCS — 0.9": feature_selected_lcs_results,
    "Random Forest": rf_results,
    "Decision Tree": dt_results,
    "Logistic Regression": lr_results,
}

metrics = [
    "Accuracy", "Balanced Accuracy", "Macro Precision",
    "Macro Recall", "Macro F1"
]

comparison_rows = [raw_lcs_row]

for model_name, fold_results in cv_models.items():
    row = {
        "Model": model_name,
        "Validation": "5-fold CV",
    }

    for metric in metrics:
        row[metric] = fold_results[metric].mean()

    comparison_rows.append(row)

comparison_table = pd.DataFrame(comparison_rows)
display(comparison_table.round(4))

# The raw eLCS used different records and a different validation method.
# Compare its numbers descriptively; compare the five-fold rows directly.

,Model,Validation,Accuracy,Balanced Accuracy,Macro Precision,Macro Recall,Macro F1
0,Original eLCS — raw data,80/20 split,0.7184,0.3589,0.3435,0.3589,0.3225
1,Original eLCS — cleaned data,5-fold CV,0.5941,0.2983,0.3693,0.2983,0.2689
2,Feature-selected eLCS — 0.9,5-fold CV,0.5942,0.2988,0.2967,0.2988,0.2697
3,Random Forest,5-fold CV,0.6143,0.3106,0.3160,0.3106,0.2832
4,Decision Tree,5-fold CV,0.4621,0.2735,0.2739,0.2735,0.2734
5,Logistic Regression,5-fold CV,0.4237,0.3802,0.3506,0.3802,0.3122


# Background information to know before going through the comparison. 

## Performance Metrics. 

### Accuracy.
 correct predicitions divided by all predictions. What fraction of patients got the correct label?

#### Percision P. 
TP/(TP + FP). When the model predicts THIS class, how often is it correct?
#### Recall R. TP/(TP + FN). 

Of the patients in THIS class, how many did it find?
#### F1. 2PR/(P + R). 

How well does it combine percision and recall for THIS class?
#### Macro Percision. 

Mean of the five class percisions. How precise is it when EVERY class counts equally?
#### Macro F1. 
Mean of the five class F1 scores. How good is its percision-recall balance ACROSS classes. 

#### Balanced Accuracy. 
ean of the five class recalls. How accurate is it across classes when each gets equal weight?

### K-fold Cross Validation.
Divide the cleaned dataset into five distinct parts, called folds. TRAIN a FRESH model on FOUR folds and TEST on ONE fold. Repeat this sequence 5 times, rotating the test fold each time. Every record appears in a test fold once, giving us 5 sets of metrics. We used StratifiedKFold which aims to keep the same proportions for each of the 5 classes in each fold. This is important because class 4 only had 39 instances. each test fold gets 7-9 of them rather than isolating them, risking a fold with 0 of those instances. 

Why use the Kfold? A single 80/20 split can cause results to dependly heavily on which few rare patients happeneded to land in the test set itself. 5 folds give us several checks of model performance. It also lets us compare the different models on the SAME TEST PORTIONS, provided each model uses the same dataset and fold setting (which it did). 

An important limit. CV doesn't auto prevent leakage. Anything learnt from the data (scaling, imputation or feature selection) based on target labels must be fitted using each folds training data only. 

### Confusion Matrix.
TP - true positive, FP - false positive, TN - true negative, FN - false negative. 
Confusion matric puts the actual classes in the rows and predicted classes in the columns. Therefore by geometry, a diagonal number is correct; an off-diagonal number is a mistake. 
Basically, zeros in the diagonal = bad, zeroes in the off-diagonal = good. (ish). If you are still confused, I will use an example in the comparison, it'll click. 


# Background of the MLMs. 

## Decision Tree Classifier. 
What. A decision tree predicts something by asking a sequence of questions about the features. A easy path to understand would be: "Is the coma score > a threshold?" If yes, "Is the physiological score > another threshold?". EVERY patient follows ONE path to a final leaf, which assigns a class to THAT patient. btw those are example questions, idk what the real questions are, just to visualise the flow. 

How. At each branch the DT algorithm searches for a feature and threshold that separates the training labels. It repeats this process within each new branch. For our classification, DecisionTreeClassifier default settings measure how mixed that classes are at a node. A tree that keeps making new branches can memorise training examples and generalise poorly. There are built-in commands which control the depth and leafs. 

Why and When. Similar to LCS, it captures non-linear relationships/interactions well, without us specifiying them first. it is also easy-ish to inspect, as in you can follow a path behind a prediction so it has good interpretability. This MLM is probably the best conventional baseline against our rule-based eLCS. It's weakness/limitation is stability, changing the training data will produce a different tree. 

## Random Forest Classifier.
What. This classifier is an upgrade to the decision tree, it combines multiple of them. Each tree trains on a random sample of training instances and considers a random subset of features when making splits. This makes each tree unique-ish. For use in classification, their predicted class probablities are combined to make the final prediction. 

Why combine? One tree might latch onto an accidental pattern (our dataset probably got it all). if multiple somewhat different trees predict together, those individual errors can cancel out. This leads to more stable predictions (could be considered an observed weakness of DTC) than one tree but you can no longer explain the path behind a prediction as easily. 

When. It is a really good starting model when relationships may be non linear and features interact. RFC does not need numerical featured stanardised but it should still be checked class by class. (ty confusion matrix). 

## Logistic Regression Classifier. 
Even though its called regression it is a classifier model. it works by learning a score from the given input features, converts these scores into class probability and then predicts a class. Our problem has 5 class so the configured model handles multi-class prediction rather than binary classification. For numerical features, think of a co-efficient, how much THAT feature changes a class's score value when OTHER inputs are held fixed. The relationship is relatively simple unless you add features representing curves/interactions. The simplicity makes our model useful as a benchmark. 

The model I ran did 3 things differently, which I indexed in its block. 

StandardScaler puts numerical inputs on a comparable scale to avoid blowing this or that out of proportion. It aids fitting and causes the model to treat the learned coefficients consistently.

OneHotEncoder (oo la la) gives nominal catogeories separate indicator columns _enum. But remember that a code (ie. race) of 3 does not represent numerical superiority to class code of 2 or 1. As i'm sure its drilled into our heads at this point. 

class_weoght="balanced" givers rarer classes (like 4/5) more weight during the training, based on its frequency in THAT training fold. The scaler and encoder sit inside the models pipeline so each fold learns from its training portion and applies it to its test portion. 

In [ ]:
display(comparison_table.round(4))
#
#
print("Confusion Matrix of the model with p of 0.9 threshold:")
print(zeroNine_confusion_matrix)
print("\nRandom Forest Confusion Matrix:")
print(rf_confusion_matrix)
print("\nDecision Tree Confusion Matrix:")
print(dt_confusion_matrix)
print("\nLogistic Regression Confusion Matrix:")
print(lr_confusion_matrix)

,Model,Validation,Accuracy,Balanced Accuracy,Macro Precision,Macro Recall,Macro F1
0,Original eLCS — raw data,80/20 split,0.7184,0.3589,0.3435,0.3589,0.3225
1,Original eLCS — cleaned data,5-fold CV,0.5941,0.2983,0.3693,0.2983,0.2689
2,Feature-selected eLCS — 0.9,5-fold CV,0.5942,0.2988,0.2967,0.2988,0.2697
3,Random Forest,5-fold CV,0.6143,0.3106,0.3160,0.3106,0.2832
4,Decision Tree,5-fold CV,0.4621,0.2735,0.2739,0.2735,0.2734
5,Logistic Regression,5-fold CV,0.4237,0.3802,0.3506,0.3802,0.3122


Confusion Matrix of the model with p of 0.9 threshold:
[[2045  903    6    6    0]
 [ 602 2324   14    8    0]
 [ 129  403    2    1    0]
 [ 424  454    3   10    0]
 [  30    9    0    0    0]]

Random Forest Confusion Matrix:
[[2233  704    1   22    0]
 [ 660 2271    0   17    0]
 [ 150  377    0    8    0]
 [ 444  422    0   25    0]
 [  31    8    0    0    0]]

Decision Tree Confusion Matrix:
[[1663  709  170  387   31]
 [ 745 1531  298  369    5]
 [ 155  246   63   70    1]
 [ 333  330   71  150    7]
 [  20    9    1    9    0]]

Logistic Regression Confusion Matrix:
[[1334  343  320  436  527]
 [ 284 1341  682  381  260]
 [  50  169  164   83   69]
 [ 163  175  146  270  137]
 [  13    5    2    4   15]]


# Comparison. 

## What does this table show and tell us?
Raw eLCS is the required original baseline but it's marginally higher scores do not show that raw data works better, we know this. Its test patients, validation methods and available predictors differe from the cleaned data-experiments. Some raw predictors contain leaked data available >3day mark. Therefore the accuracy drop (raw of 0.7184 vs. cleaned of 0.5941) cannot be accredited solely to cleaning. Removing future information and changing the evaluation collection will clearly affect the accuracy. 

Feature selection produced, an extremely small numerical change. the 0.9 p threshold eLCS lowered available predictors from 20 to 15. Against the original raw eLCS its performance values gained very little improvement while its Macro F1 score actually fell from 0.3693 to 0.2967. 

Random Forest has the best overall accuracy out of all models tested on clean data. It scores 0.6143, compared with 0.5941 for cleaned eLCS, its Macro F1 is also higher. This would suggest it classfies the numerous common-class patients more successfully, but its balanced accuracy of 0.3106 shows much weaker performance when each class is equally important. 

Logistic regression makes the strongest across class showing. Its accuracy is much lower than the forests, but its balanced accuracy and Macro F1 are the highest in direct 5-fold comparison. The stated balancedClass setting makes it so the predictions for rarer classes are encouraged. This resulted in better rare-class recal alongside more false positives. 

The single decision tree ranks below the forest in accuracy and balanced accuracy (as to be expected). It scored accuracy 0.4621 and Bal-accuracy 0.2735. Its Macro F1 is slightly above both cleaned eLCS runs. This is why having multiple metrics side-by-side is important, it allows quick comparision of many metrics rather than letting us call one model universally better. 

## What the confusion matrices did. 
The 3 less common cleaned data classes contained 535 Class 3, 891 Class 4 and just 39 Class 5 patients. 
The Original cleaned (OC) eLCS, Feature selected (FS) eLCS and Random Forest mostly predict the two large classes. The FS eLCS identified none of 39 - coma/intub patients. LR model found 15/39 but only 15 of its >1000 predictions of that class were correct, giving it a very low accuracy for that class. Therefore, better recall comes with a big false positive cost, which isn't bad but undesirable. 

## How do the other FS eLCS Variants fair?
From Daliahs P0.9 to P0.1, it can clearly be stated that 0.9 has the highest Macro F1 and overall scores. Therefore, more aggressive removal worses performance. Why did 0.5 and 0.4 have the same results? They retained the exact same features. 

## Possible limit. 
The threshold was selected after examining feature tests and variant results from clean dataset. Because that selection was not repeated INSIDE EACH TRAINING FOLD, its 5-fold score could be a happy score, optimistic. 

# Conclusion.
On the common cleaned data evaluation: RFC wins on overall accuracy, LRC wins on balanced accuracy and Macro F1. The 0.9 FS eLCS uses fewer predictors and changes performance only marginally from the OC eLCS. All models have limitations on rare class identification, with LRC being the only one which trades alot of false positives for higher rare-class recall.